version: '3.8'

services:
  slego_app:
    build: .
    container_name: slego_app_container
    ports:
      - "5006:5006"
    volumes:
      - ./slegospace:/workspace/slegospace
    environment:
      PYTHONUNBUFFERED: "1"
      JUPYTER_ENABLE_LAB: "yes"
